//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string SDT { get; set; }
        public string CCCD { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> NgayNhanPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> IDPhong { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ThongTinPhongCuaKhachSan ThongTinPhongCuaKhachSan { get; set; }
    }
}
