//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinPhongCuaKhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinPhongCuaKhachSan()
        {
            this.DatPhongs = new HashSet<DatPhong>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int IDPhong { get; set; }
        public string TenPhong { get; set; }
        public string KichThuocPhong { get; set; }
        public string GiaPhong { get; set; }
        public string TienNghiPhongTam1 { get; set; }
        public string TienNghiPhongTam2 { get; set; }
        public string TienNghiPhongTam3 { get; set; }
        public string TienNghiPhongTam4 { get; set; }
        public string HuongTamNhin1 { get; set; }
        public string HuongTamNhin2 { get; set; }
        public string TienNghiPhong1 { get; set; }
        public string TienNghiPhong2 { get; set; }
        public string TienNghiPhong3 { get; set; }
        public string TienNghiPhong4 { get; set; }
        public string TienNghiPhong5 { get; set; }
        public string TienNghiPhong6 { get; set; }
        public string HutThuoc1 { get; set; }
        public string HutThuoc2 { get; set; }
        public string UuDai { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IDKhachSan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ThongTinKhachSan ThongTinKhachSan { get; set; }
    }
}
